### ISSUE TITLE
Can't prepare a query with more then 130 fields

### ISSUE THREAD

**Issue by VytorCalixto** [MonetDB/monetdb-pool-nodejs#2]
Node version: v6.11.1
npm version: 3.10.10
monetdb-pool-nodejs version: 0.0.8
OS: Debian 9

I have the following query:

```sql
COPY SELECT ano_censo, id, nome_escola, cod_orgao_regional_inep, 
situacao_de_funcionamento, inicio_ano_letivo, termino_ano_letivo, estado_id, 
municipio_id, cod_distrito, dependencia_adm_id, cod_localizacao, 
categoria_escola_privada, conveniada_pp, tipo_convenio_pp, 
mant_escola_privada_emp, mant_escola_privada_ong, 
mant_escola_privada_sind, mant_escola_privada_sist_s, 
mant_escola_privada_s_fins, documento_regulamentacao, func_predio_escolar,
 func_salas_empresa, func_socioeducativa, func_unid_prisional, func_templo_igreja, 
func_casa_professor, func_galpao, func_salas_outros, func_salas_outra_esc,
 escola_predio_comp, agua_filtrada, agua_rede_publica, agua_poco_artesiano, 
agua_cacimba, agua_fonte_rio, agua_inexistente, energia_rede_publica, energia_gerador, 
energia_outros, energia_inexistente, esgoto_rede_publica, esgoto_fossa, esgoto_inexistente, 
lixo_coleta_periodica, lixo_queima, lixo_joga_outra_area, lixo_recicla, lixo_enterra, lixo_outros, 
sala_diretoria, sala_professor, lab_informatica, lab_ciencias, sala_atendimento_especial, 
quadra_esportes_coberta, quadra_esportes_descoberta, cozinha, biblioteca, sala_leitura, 
parque_infantil, bercario, sanitario_fora_predio, sanitario_dentro_predio, sanitario_ei,
 sanitario_pne, dependencias_pne, secretaria, banheiro_chuveiro, refeitorio, despensa, 
almoxarifado, auditorio, patio_coberto, patio_descoberto, alojam_aluno, alojam_professor, 
area_verde, lavanderia, outras_dependencias, num_salas, num_salas_utilizadas, num_tv, 
num_videocassete, num_dvd, num_parabolica, num_copiadora, num_retroprojetor, 
num_impressora, num_som, num_multimidia, num_fax, num_foto, num_computador, 
num_computador_adm, num_computadpr_aluno, internet, internet_banda_larga, 
num_funcionarios, alimentacao, aee, atividade_complementar, ensino_regular, 
reg_infantil_creche, reg_infantil_preescola, reg_medio_medio, reg_medio_integrado, 
reg_medio_normal, reg_medio_prof, ensino_especial, esp_infantil_creche, 
esp_exclusiva_creche, esp_exclusiva_medio_medio, esp_exclusiva_medio_integrado, esp_exclusiva_medio_normal, esp_exclusiva_prof, esp_eja_fund, esp_eja_medio, 
ensino_eja, ensino_eja_fund, ensino_eja_medio, fundamental_ciclos,
 localizacao_diferenciada_id, material_esp_nao_utilza, 
material_esp_quilombola, material_esp_indigena, educacao_indigena, 
cod_lingua_indigena, espaco_turma_pba, abre_final_de_semana, 
proposta_pedag_altern, eja_projovem, fundamental_8_anos, fundamental_9_anos, 
lingua_indigena, lingua_portuguesa, fundamental_regular_8_anos,
 fundamental_regular_9_anos, regiao_id, cod_mesorregiao, cod_microregiao, 
escola_sede_vinculada_id, ies_vinculada_id, local_func_predio_escolar,
 local_func_prisional_socio, local_func_galpao, quadra_esportes, biblioteca_sala_leitura, 
equip_tv, equip_videocassete, equip_dvd, equip_parabolica, equip_copiadora, 
equip_retroprojetor, equip_impressora, equip_impressora_mult, equip_som, 
equip_multimidia, equip_fax, equip_foto, equip_computadores, num_impressora_mult, 
indigena_lingua, mediacao_presencial, mediacao_semi_presencial, mediacao_ead, 
educacao_profissional, reg_fund_ai, reg_fund_af, reg_esp_exclusiva_fund_ai, 
reg_esp_exclusiva_fund_af, ensino_eja_prof, ensino_esp_exclusiva_eja_prof, 
dependencia_adm_priv, fornecimento_agua, fornecimento_energia, esgoto_sanitario, 
localidade_area_rural 
FROM escola 
WHERE (escola.ano_censo >= 2015 ) AND (escola.ano_censo <= 2015 ) 
INTO '/tmp/escola-1505227204230.csv' USING DELIMITERS ';';
```
When preparing it with monetdb-pool I get the following error:

```
Error: SELECT: identifier 'eja_projovem' unknown
    at _handleResponse (/home/simcaq/cdn-dev/node_modules/monetdb/src/mapi-connection.js:223:41)
    at _handleData (/home/simcaq/cdn-dev/node_modules/monetdb/src/mapi-connection.js:152:13)
    at Socket._onData (/home/simcaq/cdn-dev/node_modules/monetdb/src/mapi-connection.js:422:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

The query is valid and executes on mclient. If I use at max 130 fields, the query runs without problems.

**Comment by kutsurak** [comment]
Hello Vytor,

This issue fell somehow through the cracks. I apologize for that. Did it finally work for you?

Best regards,
Panos
